sudo: false
language: cpp
# sudo: required
dist: trusty
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
os:
- linux
- osx
compiler:
- clang
- gcc
# before_script:
# - sudo apt-get install libboost-system-dev libboost-filesystem-dev
script:
- cmake -DCMAKE_BUILD_TYPE=Release && make -j4
