sudo: false
language: cpp
sudo: required
dist: trusty
os:
- linux
- osx
compiler:
- clang
- gcc
before_script:
- sudo apt-get install libboost-system-dev libboost-filesystem-dev
script:
- cmake -DCMAKE_BUILD_TYPE=Release && make -j4